SpokaneTech/SpokaneTech_Py

- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
- .github/ISSUE_TEMPLATE/question.yaml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/STYLE_GUIDE.md
- LICENSE
for issue #14 
Adding some basic repo stuff including style guide, coc, pr template and issue templates. Keeping these (except for the license) under .github to maintain a clean base directory.
> adding license, style guide, issue templates, coc, and contributing docs

- src/spokanetech/settings.py
> Stand up basic website

- .dockerignore
- .github/workflows/deploy.yml
- Dockerfile
- fly.toml
- requirements.txt
- src/spokanetech/settings.py
issue #3
- Add config to deploy app to Fly.io
- Add [dj-django-url](https://pypi.org/project/dj-database-url/) to automatically read `DATABASE_URL` environment variable
- Add basic workflow to deploy to Fly.io on merge to main
~~🛑 blocked on https://github.com/SpokaneTech/SpokaneTech_Py/pull/16 merging~~
https://spokanetech.org
> Add Fly.io config

- docs/Infrastructure.md
- fly.toml
- Fix [fly console](https://fly.io/docs/flyctl/console/) command path
- Add basic infrastructure notes
- #3
**Checklist:**
> fix: Fly.io `console_command` path

- .github/workflows/bandit.yaml
- .github/workflows/ruff.yaml
- Fix CI workflows not running for pull requests
**Checklist:**
> fix: CI workflows not running for PRs

- src/spokanetech/settings.py
- src/web/views.py
Minor code fixes to pass CI. 
Also fixes 500 error on live site.
- Closes #26 
**Checklist:**
> Fix CI Failures

- fly.toml
- scripts/post_deploy.sh
- Fix static files being cleared on every deploy to production by using Fly.io's [release_command](https://fly.io/docs/reference/configuration/#run-one-off-commands-before-releasing-a-deployment) config
- fixes #31
**Checklist:**
> Add fly.io release_command and script

- src/spokanetech/settings.py
- Add `CSRF_TRUSTED_ORIGINS` for hosts
- closes #29
**Checklist:**
> Add `CSRF_TRUSTED_ORIGINS` for hosts

- Dockerfile
- scripts/post_deploy.sh
- Move `collectstatic` to the Dockerfile so static files are in all Fly.io container instances
- #30
**Checklist:**
> #30: Move `collectstatic` to Dockerfile

- .env.template
- .github/CONTRIBUTING.md
- .github/STYLE_GUIDE.md
- Dockerfile
- docs/infrastructure.md
- requirements.txt
- scripts/post_deploy.sh
- src/spokanetech/backend.py
- src/spokanetech/settings.py
- Add Azure for backend media and static storage
- Use [`django-storages`](https://django-storages.readthedocs.io/) for this 
- closes #47
**Checklist:**
> #47: Add Azure for backend media and static storage

- requirements.txt
- src/templates/spokanetech/navbar.htm
- src/web/templates/web/partials/modal/detail_event.htm
- src/web/tests/test_views.py
- src/web/urls.py
- src/web/views.py
Closes issue 53. This change adds a monthly calendar view of events with events details available via modal. Also added a link to discord. 
- #1
- #2
**Checklist:**
> 53 feature request add a calendar view of events

- docs/celery.md
- docs/infrastructure.md
- fly.toml
- mkdocs.yml
- requirements.txt
- src/spokanetech/__init__.py
- src/spokanetech/celery.py
- src/spokanetech/settings.py
- Add [Celery](https://docs.celeryq.dev/en/stable/getting-started/introduction.html) to support background tasks
- Add Celery.md docs page with links to more docs
- Add Celery broker process to Fly.io config
- Add standard Django + Celery packages to requirements.txt
- closes #58
**Checklist:**
> Add Celery

- fly.toml
- Fix worker misspelled as "wokrer" in Fly config
**Checklist:**
> Fix worker spelled wrong in fly.toml

- .github/STYLE_GUIDE.md
- mkdocs.yml
- Improve the readability of the docs style guide by fixing markdown formatting errors and adding code syntax highlighting
- fixes #65
**Checklist:**
Before
After
> Improve docs style guide

- src/web/admin.py
- src/web/models.py
- src/web/scrapers.py
- src/web/services.py
- src/web/templatetags/web_extras.py
- src/web/tests/test_scrapers.py
- src/web/tests/test_services.py
- src/web/tests/test_tasks.py
- src/web/tests/test_templatetags.py
- src/web/tests/test_views.py
- src/web/urls.py
- src/web/views.py
- Fix formatting violations by formatting project with [ruff](https://docs.astral.sh/ruff/)
- #78
**Checklist:**
> Format project with ruff

- src/web/views.py
- Order events soonest-to-latest by date_time
- Fixes #90
**Checklist:**
> #90: Order events by date_time

- requirements/dev.txt
- src/spokanetech/settings.py
- src/spokanetech/urls.py
- Add [Django Debug Toolbar
](https://django-debug-toolbar.readthedocs.io/en/latest/index.html)    - Only enabled when `DEBUG=True`
- closes #84 
**Checklist:**
> #84: Add Django Debug Toolbar

- src/templates/spokanetech/base.html
- src/web/middleware.py
- src/web/models.py
- src/web/scrapers.py
- Fix user's timezone not being used if it's in local storage but they have a new session
- Add default sorting to models
- #87
**Checklist:**
https://github.com/SpokaneTech/SpokaneTech_Py/assets/19392916/44dd0934-08f7-45df-b2eb-c4ad5cd0a0fb
> Fix user timezone not being used

- src/static/main.css
Fix menu list styling displaying list bullets
fixes #111
**Checklist:**
Before
After
> Fix menu list styling displaying list bullets

- src/web/scrapers.py
Only scrape first upcoming event for a series of events.
Normal (i.e one-off events, past events, and the next event in a repeating event series) have numeric event urls; while future events have alphabetical IDs.
Additionally, some events (like [today's Coffee & Code](https://www.meetup.com/python-spokane/events/302271687/)) don't have tags on Meetup, so they won't have tags on SpokaneTech too ([see here](https://spokanetech.org/events/126)).
- #112 
**Checklist:**
> Fix 112: Duplicated Meetup events.

- .github/workflows/bandit.yaml
- .github/workflows/ruff_format.yaml
- .github/workflows/ruff_lint.yaml
- .github/workflows/test.yaml
- dagger.json
- dagger/src/linters.py
- dagger/src/main.py
- docs/CONTRIBUTING.md
- pyproject.toml
- requirements.dev.lock
Upgrade Dagger to `v0.12.6`, Add context directory support.
Closes #122 
**Checklist:**
> Update Dagger to v0.12.6

- README.md
Provide a brief description of the changes introduced by this pull request.
- #15 
**Checklist:**
> Update README: Add contribution info and links.

- .github/workflows/deploy_docs.yaml
> Actions: Docs: Remove leading slash

- docs/CONTRIBUTING.md
Add instructions for adding new dependencies using `uv`.
- Closes #128
Note: PR #130 should be merged first.
**Checklist:**
> Add instructions for adding new dependencies using `uv`.

- src/web/templates/web/partials/detail_tech_group.htm
- src/web/views.py
Adds Event cards for upcoming events when looking at an event group.
- Closes #48 
**Checklist:**
> Add Upcoming events to tech group page.

- README.md
> Fix bad link to spokanetech.org

- .gitignore
- src/web/forms.py
- src/web/templates/web/partials/detail_event.htm
- src/web/templates/web/partials/event_list.htm
Add Event image to form and templates
- #76
**Checklist:**
> Add Event image to form and templates
